name: Auto Renew Server

on:
  schedule:
    # Cada 7 horas (00:00, 07:00, 14:00, 21:00 UTC)
    - cron: '0 */7 * * *'
  workflow_dispatch: # permite ejecutarlo manualmente

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Puppeteer
        run: npm install puppeteer

      - name: Ejecutar script de renovación
        env:
          MC_USER: ${{ secrets.MC_USER }}
          MC_PASS: ${{ secrets.MC_PASS }}
        run: node index.js
