name: Auto Renew Server

on:
  schedule:
    - cron: "0 */7 * * *" # cada 7 horas
  workflow_dispatch:

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repo
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar renovación
        env:
          MCSERVER_USER: ${{ secrets.MCSERVER_USER }}
          MCSERVER_PASS: ${{ secrets.MCSERVER_PASS }}
        run: npm start
