name: Auto Renew Server

on:
  schedule:
    # cada 7 horas (cron en UTC)
    - cron: '0 */7 * * *'
  workflow_dispatch:

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run renew script
        env:
          MC_USER: ${{ secrets.MC_USER }}
          MC_PASS: ${{ secrets.MC_PASS }}
        run: node index.js
